---
title: "Untitled"
author: "Christian Cole"
date: "06/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jsonlite)
library(lubridate)
library(ggplot2)

raceToDf = function(race) {
  # extract the required info from the json
  race.df = data.frame(Trump = race$timeseries[[1]]$vote_shares$trumpd, 
                     Biden = race$timeseries[[1]]$vote_shares$bidenj, 
                     Votes = race$timeseries[[1]]$votes, 
                     Time = race$timeseries[[1]]$timestamp)
# create new columns for Biden - Trump difference and percentage of total votes
  race.df = cbind(race.df, 
                  Diff = race.df$Biden - race.df$Trump, 
                  Count_pc = race.df$Votes/race$tot_exp_vote)
  return(race.df)

}

```

## R Markdown


```{r nevada}

nv.json = fromJSON('https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/nevada/president.json')

df = raceToDf(nv.json$data$races)
# get last time
d = ymd_hms(tail(df,1)$Time)

ggplot(df, aes(x = Count_pc, y = Diff)) + 
  labs(title = 'Nevada',
       caption = paste('Last update:', format(d, "%H:%M %d %b")),
       x = 'Percentage of expected vote',
       y = 'Biden lead') +
  geom_rect(aes(xmin = 0.65, ymin = 0, xmax = 1, ymax = 0.05), fill = 'blue', alpha = 0.8) +
  geom_rect(aes(xmin = 0.65, ymin = -0.01, xmax = 1, ymax = 0), fill = 'red', alpha = 0.8) +
  geom_smooth(method = 'lm') +
  geom_point() + 
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(-0.01, 0.05), labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(limits=c(0.65,1), labels = scales::percent_format(accuracy = 0.1)) +
  theme_minimal()



```
```{r georgia, fig.width=9}

ga.json = fromJSON('https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/georgia/president.json')

df = raceToDf(ga.json$data$races)
# get last time
d = ymd_hms(tail(df,1)$Time)

ggplot(df, aes(x = Count_pc, y = Diff)) + 
  labs(title = 'Georgia',
       caption = paste('Last update:', format(d, "%H:%M %d %b")),
       x = 'Percentage of expected vote',
       y = 'Biden lead') +
  geom_rect(aes(xmin = 0.65, ymin = 0, xmax = 1, ymax = 0.01), fill = 'blue', alpha = 0.8) +
  geom_rect(aes(xmin = 0.65, ymin = -0.05, xmax = 1, ymax = 0), fill = 'red', alpha = 0.8) +
  geom_smooth(method = 'lm') +
  geom_point() + 
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(-0.05, 0.01), labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(limits=c(0.65,1), labels = scales::percent_format(accuracy = 0.1)) +
  theme_minimal()



```

```{r pennsylvania}

pa.json = fromJSON('https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/pennsylvania/president.json')

df = raceToDf(pa.json$data$races)
# get last time
d = ymd_hms(tail(df,1)$Time)

ggplot(df, aes(x = Count_pc, y = Diff)) + 
  labs(title = 'Pennsylvania',
       caption = paste('Last update:', format(d, "%H:%M %d %b")),
       x = 'Percentage of expected vote',
       y = 'Biden lead') +
  geom_rect(aes(xmin = 0.65, ymin = 0, xmax = 1, ymax = 0.01), fill = 'blue', alpha = 0.8) +
  geom_rect(aes(xmin = 0.65, ymin = -0.05, xmax = 1, ymax = 0), fill = 'red', alpha = 0.8) +
  geom_smooth(method = 'lm') +
  geom_point() + 
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(-0.05, 0.01), labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(limits=c(0.65,1), labels = scales::percent_format(accuracy = 0.1)) +
  theme_minimal()
```



```{r arizona}

az.json = fromJSON('https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/arizona/president.json')

df = raceToDf(az.json$data$races)
# get last time
d = ymd_hms(tail(df,1)$Time)

ggplot(df, aes(x = Count_pc, y = Diff)) + 
  labs(title = 'Arizona',
       caption = paste('Last update:', format(d, "%H:%M %d %b")),
       x = 'Percentage of expected vote',
       y = 'Biden lead') +
  geom_rect(aes(xmin = 0.65, ymin = 0, xmax = 1, ymax = 0.05), fill = 'blue', alpha = 0.8) +
  geom_rect(aes(xmin = 0.65, ymin = -0.01, xmax = 1, ymax = 0), fill = 'red', alpha = 0.8) +
  geom_smooth(method = 'lm') +
  geom_point() + 
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(-0.01, 0.05), labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(limits=c(0.65,1), labels = scales::percent_format(accuracy = 0.1)) +
  theme_minimal()
```